### ISSUE TITLE
Timestamp na tela de sensor data

### ISSUE THREAD

**Issue by rafaelpv** [alientronics/tpms-dashboard#53]
Adicionar data e timestamp com hora minuto e segundo na tela de sensor data de parts
![d46b46ee-3418-4341-b781-cd005a9d4e7e](https://cloud.githubusercontent.com/assets/14228330/17711717/4c1aee7c-63c9-11e6-980c-110bfad6509d.jpg)

**Comment by felipemelz** [comment]
Rafael, pode fazer essa alteração pra nós? Além da hora minuto e segundo, coloca também a data.

**Comment by felipemelz** [comment]
@rafaelpv Rafael, pode fazer essa alteração pra nós? Além da hora minuto e segundo, coloca também a data.
Além disso, consegue plotar um gráfico onde a coordenada X tem o tempo e no eixo Y você plote os seguintes dados em cores diferentes:
1 - pressão (cor Laranja)
2 - temperatura (cor azul)
3 - nível de bateria (cor Preto)

Detalhe: cria um check-box para cara tipo de dado, onde podemos escolher quais tipos de dados devem aparecem no gráfico.

Pode colocar esse gráfico acima da lista de dados.

**Comment by rafaelpv** [comment]
No caso, onde ficaria o gráfico? Em uma nova aba? Ou abaixo da tabela?

**Comment by felipemelz** [comment]
Rafael, pensei com mais calma e percebi que é melhor adicionarmos o gráfico em outro lugar, na visualização do veículo. Mas para não confundir, vou abrir uma nova issue só sobre isso.

**Comment by rafaelpv** [comment]
Fiz essa modificação, adicionei data e hora na tabela

Em 27 de setembro de 2016 18:10, Felipe Werle Melz <notifications@github.com
