### ISSUE TITLE
Adição de informações na listagem de parts

### ISSUE THREAD

**Issue by rafaelpv** [alientronics/tpms-dashboard#54]
Adicionar Nome, Número e posição na listagem de parts (quando é pneu ou sensor) 
![bc8291b9-ca34-4493-8f12-3d390d512f88](https://cloud.githubusercontent.com/assets/14228330/17711763/7eb048aa-63c9-11e6-8448-cc9829687168.jpg)

**Comment by felipemelz** [comment]
Rafael, faltou adicionar a posição do pneu e do sensor na lista.

**Comment by rafaelpv** [comment]
Corrigido, valeu

**Comment by felipemelz** [comment]
@heukirne atualiza no sistema essa correção pra nós?

**Comment by felipemelz** [comment]
Valeu! 100% agora!
