### ISSUE TITLE
Arrumar códigos sensores nas posições do mapa de pneus- Teste Minuano

### ISSUE THREAD

**Issue by felipemelz** [alientronics/tpms-dashboard#57]
Atualizar posições dos pneus conforme códigos de sensores atuais do veículo, da imagem em anexo.

![mapa de pneus veiculo mbp-4666](https://cloud.githubusercontent.com/assets/17277816/18893068/a70beac2-84e2-11e6-93d2-2840e4ce0f29.png)

**Comment by rafaelpv** [comment]
Não entendi. É para trocar o número da posição que está dentro do pneu pelo código? Se for, não vai caber esse código dentro do pneu e teremos que reajustar o layout

**Comment by felipemelz** [comment]
Rafael, na verdade esse pedido foi para o Henrique. Não sabia que tu ia receber isso também mesmo eu dando assign só no Henrique.

**Comment by rafaelpv** [comment]
Certo, não tinha visto, desculpa

2016-09-27 23:16 GMT-03:00 Felipe Werle Melz notifications@github.com:
