### ISSUE TITLE
Corrigir bug ao editar itens ou acesso aos Atributos

### ISSUE THREAD

**Issue by felipemelz** [alientronics/tpms-dashboard#62]
![33](https://cloud.githubusercontent.com/assets/17277816/20141166/4e00f944-a676-11e6-97ea-f79bcca5cd1f.png)
![34](https://cloud.githubusercontent.com/assets/17277816/20141167/4e0152b8-a676-11e6-80d5-3a11852a98e2.png)
![image](https://cloud.githubusercontent.com/assets/17277816/20141576/21ad7122-a678-11e6-9cae-93f9f9ce0c56.png)

**Comment by rafaelpv** [comment]
Testei com o código que tenho na minha máquina e funcionou. @heukirne , pode me liberar o log de quando ocorre este problema, por favor? Obrigado

**Comment by heukirne** [comment]
Acho que era problema no chave da Api. Testa de novo @felipemelz

**Comment by felipemelz** [comment]
Agora está funcionando normalmente, obrigado @rafaelpv e @heukirne
