### ISSUE TITLE
Gráfico do histórico de sensores não está aparecendo para mim

### ISSUE THREAD

**Issue by felipemelz** [alientronics/tpms-dashboard#63]
![32](https://cloud.githubusercontent.com/assets/17277816/20141201/786bc5c4-a676-11e6-97f3-94a9c815ebf8.png)

**Comment by rafaelpv** [comment]
Felipe, não aparece em casos onde não há informações de sensor para serem exibidas. Colocar uma mensagem avisando sobre isso, é suficiente? Alguma mensagem em específico, nesse caso, ou posso colocar apenas "nenhum resultado encontrado"?

**Comment by felipemelz** [comment]
Rafael, acho que assim está bom:
PORTUGUÊS: "Não há dados para este período e pneus selecionados"
INGLÊS:"There is no data available for this tires and time frame chosen."

**Comment by rafaelpv** [comment]
Resolvido
