### ISSUE TITLE
visualizador de pressão dinâmico aparece borrado

### ISSUE THREAD

**Issue by felipemelz** [alientronics/tpms-dashboard#64]
![35](https://cloud.githubusercontent.com/assets/17277816/20141275/bb11b06e-a676-11e6-9ce4-f075f8575f11.png)
![image](https://cloud.githubusercontent.com/assets/17277816/20141301/ddde3c7a-a676-11e6-97dd-5ceee8517530.png)

**Comment by rafaelpv** [comment]
Resolvido

**Comment by felipemelz** [comment]
@rafaelpv pra mim continua a mesma coisa ainda, será que é meu computador?

**Comment by rafaelpv** [comment]
O Henrique chegou a atualizar? Se atualizou, tenta segurar crtl e apertar f5, pra atualizar..

**Comment by rafaelpv** [comment]
Se continuar me avisa, por favor

**Comment by felipemelz** [comment]
O Henrique não tinha atualizado. Agora foi! Valeu!
