### ISSUE TITLE
How can i deploy it online on servers?

### ISSUE THREAD

**Issue by deltaforce3** [alientronics/tpms-dashboard#70]
I want to deploy it online using the hosting service provdided such as hostgator/hostinger etc.

Can you please guide how to deploy it online and use it as the web applcation.

**Comment by heukirne** [comment]
I use this script to deploy the web-repo at my server:
https://gist.github.com/heukirne/a93cd5717e9bba3a46ef355e71dc927f

But the are also the IBM Bluemix Guide:
https://github.com/alientronics/fleetany-web/wiki/Deploy-in-Bluemix

The bootstrap is create a mysql, clone de repo and run artisan seed

> mysql -e 'create database fleetany;'
> git clone https://github.com/alientronics/fleetany-web
> cd fleetany-web
> php artisan migrate:refresh --seed --force
